app:
  api:
    external:
      url: https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos
      api-key: DEMO_KEY
    headers:
      sol: sol
      camera: camera
      api-key: api_key

server:
  port: 8080

spring:
  datasource:
    username: ec2_rds_postgres_user
    url: jdbc:postgresql://aws-rds-pic-db.cfrrhg7oeu3i.eu-north-1.rds.amazonaws.com:5432/picdb?ssl=true&sslmode=require
    hikari:
      max-lifetime: 840000
      jdbc-url: jdbc:postgresql://aws-rds-pic-db.cfrrhg7oeu3i.eu-north-1.rds.amazonaws.com:5432/picdb?ssl=true&sslmode=require
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
